### ISSUE TITLE
Missing acr causes error

### ISSUE THREAD

**Issue by klaalo** [CSCfi/shibboleth-idp-oidc-extension#1]
If acr is not defined in request, runtime exception is caught

`2018-04-12 07:18:20,768 - ERROR [net.shibboleth.idp.saml.profile:-2] - Uncaught runtime exception java.lang.RuntimeException: Invalid parameters, programming error at org.geant.idpextension.oidc.token.support.TokenClaimsSet.<init>(TokenClaimsSet.java:137)`

Can be avoided by defining acr in authentication configuration:

`<bean parent="shibboleth.OIDCAuthnContextClassReference" c:classRef="password" />`

**Comment by jalauros** [comment]
Fixed now in HEAD.
