### ISSUE TITLE
Error loading class [org.geant.idpextension.oidc.profile.impl.PopulateOIDCSignatureSigningParameters]

### ISSUE THREAD

**Issue by dongzunan00a** [CSCfi/shibboleth-idp-oidc-extension#12]
Hi there,
I deployed this OIDC extension on top of my existing shibboleth idp.
I have setup a relying-party which connects to my shibboleth idp using OIDC profile and authorization code flow.
When I triggered the authentication flow, I got an error, "Error loading class [org.geant.idpextension.oidc.profile.impl.PopulateOIDCSignatureSigningParameters]". 

Here's the log:
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [org.geant.idpextension.oidc.profile.impl.PopulateOIDCSignatureSigningParameters] for bean with name 'PopulateIDTokenSignatureSigningParameters' defined in file [/opt/shibboleth-idp/flows/oidc/authorize/oidc-beans.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: org/opensaml/profile/action/AbstractHandlerDelegatingProfileAction
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1360)
Caused by: java.lang.NoClassDefFoundError: org/opensaml/profile/action/AbstractHandlerDelegatingProfileAction
	at java.lang.ClassLoader.defineClass1(Native Method)
Caused by: java.lang.ClassNotFoundException: org.opensaml.profile.action.AbstractHandlerDelegatingProfileAction
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1335)

I have confirmed that idp-oidc-extension-impl-0.8.0.jar is in the right place, and in the idp.war file.
Any idea of what is happening here?

Thanks,
Zunan

**Comment by jalauros** [comment]
Hi Zunan,

 To me that log suggests that you are not using Shibboleth 3.4+ but an older version instead. The extension requires 3.4.0 or higher version of Shibboleth IdP. Could that be the case?

Janne

**Comment by dongzunan00a** [comment]
Hi Janne,
You are right, I'm using Shibboleth 3.3 now. I'll switch to 3.4, and see if that works.
Thanks,
Zunan
