### ISSUE TITLE
request - consistent naming for config files.

### ISSUE THREAD

**Issue by lhoekenga** [CSCfi/shibboleth-idp-oidc-extension#14]
More current releases of the plugin have separated the oidc specific configuration out of the base shibboleth configuration files into additional files that are referenced by the stock shibboleth configuration.

However, the names are inconsistent..
attribute-filter-oidc.xml
attribute-resolver-oidc.xml
credentials-oidc.xml
global-oidc.xml
idp-oidc.properties
services-oidc.xml

versus...
oidc-metadata-providers.xml
oidc-relying-party.xml
oidc-subject.properties

I feel like there should be a single naming convention.

**Comment by jalauros** [comment]
I see your point and agree that naming is not our forte. The ship has sailed for the 1.0.0 extension though. I will close it for now as we are not doing this in the near future.
