### ISSUE TITLE
Access-token as JWT

### ISSUE THREAD

**Issue by gueuselambix** [CSCfi/shibboleth-idp-oidc-extension#22]
Hi,

First of all, thank you for this great extension!
Was it a deliberate choice to create opaque access tokens for clients? Many OAuth2.0 implementations nowaday issue access tokens in a JWT-format.
Resources could than validate the access tokens based on their signature and metadata. I believe this could be useful for shortlived access tokens. Client are now obliged to do introspection of the token, which could be a costly operation for every call to the resource.

Could it be an option to issue the access token as a JWT on the OIDC.SSO profile?

Thanks

**Comment by jalauros** [comment]
Hi,

It was a deliberate choice. We are populating both the authz code and access token with our internal information. The reasoning behind that was to have stateless as possible implementation. 

If you want to broaden the use cases from basic oidc (that was and still is our main focus) to your resource server applying access token, there is as you mentioned the  introspection endpoint for that. 

Whether there is in the future a option to have a access token as JWT remains to be seen. If there is a use case strong enough that requires it, then we will do it. I am not sure not wanting to use introspection endpoint is such.

**Comment by jalauros** [comment]
And thanks for trying  out this extension!

**Comment by gueuselambix** [comment]
Perhaps, you could encode that internal information inside a JWT?
Using a JWT as access token makes it even more stateless from the point of view of the resource.

**Comment by jalauros** [comment]
Sure, we would not even need to change our internal processing (almost) at all. We could wrap the current opaque access token inside the 'JWT Access Token' treating the 'JWT Access Token' merely as a shell for the actual token for internal processing. That would be easy. 

The problem, as I see it is what would the rest of the contents be. There is no RFC or definition for 'JWT Access Token' as far as I know. When talking about this with people that are contributing to specifications I get the impression the access token is really meant to be opaque, and that is what the specifications say also - even though leaving room for non opaque strings. That may explain why no such definition exists. What do the clients expect to have in the JWT access token? Perhaps the fields mentioned Introspection and what more? Then I have seen designs that expect to have user claims there which seems very strange to me. If we have option to create a JWT based non opaque access token, we want to do it right first time.

**Comment by gueuselambix** [comment]
Besides the default JWT-metadata, like jti, exp, iat, iss, typ, azp, auth_time, the basic access_token must contain the subject and scope values. 

example:
```json
{
  "jti": "<guid>",
  "exp": 1559031821,
  "nbf": 0,
  "iat": 1559028221,
  "iss": "<issuer>",
  "sub": "<subject>",
  "typ": "Bearer",
  "azp": "<client_id>",
  "auth_time": 1559028024,
  "acr": "0",
  "scope": "<space_seperated_scopes>",
}
```

Optionally you could include the information that can be resolved via the introspection endpoint. Perhaps controlled per attribute via a boolean switch in AttributeEncoderPluginConfiguration. 

For some resources this will be contain sufficient information to serve their resources and it will save the round-trip to the introspection endpoint.

**Comment by jalauros** [comment]
>>Besides the default JWT-metadata, like jti, exp, iat, iss, typ, azp, auth_time, the basic access_token >>must contain the subject and scope values.

Some of your example claims I would derive from Introspection RFC, some are not there. My point is that show me the OAuth2 RFC that describes JWT Access Token and we will definetely have it on the "shorter list" of things to do. My understanding is that there is no such, which puts it more in the "we might someday do" list. I am afraid not having such document may open a can of worms for us if we do it.

**Comment by gueuselambix** [comment]
There is already a draft on this topic: https://www.ietf.org/id/draft-ietf-oauth-access-token-jwt-00.txt

**Comment by jalauros** [comment]
That is a very recent draft indeed, and a early one. Something to work with anyway and brings this to another level. Nicely spotted that one, thanks. 

We will for sure follow this and cannot say why it would not be implemented. We have to of course see how this draft plays out for a while.

**Comment by gueuselambix** [comment]
The draft has reached a third revision (https://datatracker.ietf.org/doc/draft-ietf-oauth-access-token-jwt/). Would this still be something you are considering to support? 
Should I repost this issue on the shibboleth issue tracker?

**Comment by gueuselambix** [comment]
moved to https://issues.shibboleth.net/jira/projects/JOIDC/issues/JOIDC-7
