### ISSUE TITLE
Authentication for OIDCClientRegistration

### ISSUE THREAD

**Issue by gueuselambix** [CSCfi/shibboleth-idp-oidc-extension#27]
I added Basic authentication on container-level (jetty) in order to protect the oidc-client-registration endpoint (```/idp/profile/oidc/register```). But the Authorization header is passed along com.nimbusds.openid.connect.sdk.rp.OIDCClientRegistrationRequest, which eventually throws a ParseException because he expects a Bearer token:

```
ERROR [org.opensaml.profile.action.impl.DecodeMessage:73] - Profile Action DecodeMessage: Unable to decode incoming request - org.opensaml.messaging.decoder.MessageDecodingException: com.nimbusds.oauth2.sdk.ParseException: Token type must be "Bearer"
        at org.geant.idpextension.oidc.decoding.impl.OIDCClientRegistrationRequestDecoder.doDecode(OIDCClientRegistrationRequestDecoder.java:83)
Caused by: com.nimbusds.oauth2.sdk.ParseException: Token type must be "Bearer"
        at com.nimbusds.oauth2.sdk.token.BearerAccessToken.parse(BearerAccessToken.java:259)
```

Is there a way to enable the OIDC-registration endpoint with authentication? 
Perhaps I could strip the Authorization-header after validation by jetty. 

Any thoughts on this?

**Comment by hjmikkon** [comment]
Currently there's no supported way in the plugin to set up registration endpoint authentication. Basic authentication is not mentioned in the [spec](https://openid.net/specs/openid-connect-registration-1_0.html). Supporting bearer access tokens would be the standard way, but it's not implemented yet by the plugin.

If we supported access tokens for this endpoint, would for instance a command-line tool for generating access tokens be satisfactory for you? We could encode some restrictions inside the access token, for instance the list of allowed redirect_uris for the client to register. The admin using the tool would be responsible for communicating the access token for the RP admin/developer. This is just one idea, any other ideas are also welcome.

We're also following the [federation draft](https://openid.net/specs/openid-connect-federation-1_0.html) work, but the implementation on our side is not yet clearly scheduled.

**Comment by gueuselambix** [comment]
Yes, generating access tokens via CLI would be a good start. Otherwise the current OIDC dyn client registration implementation cannot be used with authentication (beside IP restrictions ) 
It would be nice if we could configure a regex to validate the redirect_uris.

**Comment by gueuselambix** [comment]
moved to https://issues.shibboleth.net/jira/projects/JOIDC/issues/JOIDC-8
