### ISSUE TITLE
Testing PKCE flow

### ISSUE THREAD

**Issue by gueuselambix** [CSCfi/shibboleth-idp-oidc-extension#31]
Hi

I am trying to get the [OAuth2 Authorization Code flow with PKCE extension ](https://tools.ietf.org/html/rfc7636) working.

I added a client configuration: 
```json
{
  "client_id": "https://spa.example.com",
  "client_name": "description",
  "logo_uri": "https://spa.example.com/logo.jpg",
  "response_types": [
    "code"
  ],
  "grant_types": [
    "authorization_code"
  ],
  "scope": "openid profile",
  "redirect_uris": ["https://spa.example.com/callback"],
  "subject_type": "public"
}
```

I can get a code:
```
https://idp.example.com/idp/profile/oidc/authorize?scope=openid%20profile&response_type=code&client_id=https%3A%2F%2Fspa.example.com&code_challenge=1854380fe9792fd611478d2f98a948a098efee3bb2ae38721efa6f69c696d00b&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fspa.example.com%2Fcallback
```
After authn, I am redirected to:
https://spa.example.com/callback?code=AApz...UeHg

When I try to resolve the code for a token:
```bash
curl --request POST \
  --url 'https://idp.example.com/idp/profile/oidc/token' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data grant_type=authorization_code \
  --data 'client_id=https://spa.example.com' \
  --data code_verifier=ooYaingahhiewie2Oofaelie6chai7phaif1dai1eeg \
  --data code=AApz...UeHg \
  --data 'redirect_uri=https://spa.example.com/callback'
```
I get:
```json
{"error_description":"AccessDenied","error":"invalid_request"}
```
Logs:
```
WARN [org.geant.idpextension.oidc.profile.impl.ValidateEndpointAuthentication:206] - Profile Action ValidateEndpointAuthentication: Unrecognized client authentication null for client_secret_basic - 
WARN [org.opensaml.profile.action.impl.LogEvent:105] - A non-proceed event occurred while processing the request: AccessDenied - 
```
Am I missing some configuration to overrule the authentication at the token endpoint? The client_secret is absent, since I am using the PKCE flow.

Thanks

**Comment by hjmikkon** [comment]
Hi,

Apologies for the delayed response.

> `{
  "client_id": "https://spa.example.com",
  "client_name": "description",
  "logo_uri": "https://spa.example.com/logo.jpg",
  "response_types": [
    "code"
  ],
  "grant_types": [
    "authorization_code"
  ],
  "scope": "openid profile",
  "redirect_uris": ["https://spa.example.com/callback"],
  "subject_type": "public"
}`

The RP configuration above shows that your token_endpoint_auth_method is not defined, and thus is considered as 'client_secret_basic'. That's why the process log also complains that the incoming client authentication (nothing/null) is not recognized as client_secret_basic. The default value for token endpoint authentication method is client_secret_basic, as defined in [Section 9 of the OIDC core](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) and [Section 2 of the OIDC dynamic client registration](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata) specs.

> The client_secret is absent, since I am using the PKCE flow.

The PKCE specification provides a way to protect the authorization code transport: it doesn't take out the need of token endpoint authentication for confidential clients.

**Comment by gueuselambix** [comment]
A single page application (SPA) is considered a public client, so you cannot store any secret information in that client.

https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication
>none
> The Client does not authenticate itself at the Token Endpoint, either because it uses only the Implicit Flow (and so does not use the Token Endpoint) or because it is a Public Client with no Client Secret or other authentication mechanism.

In order for SPAs to use the PKCE flow, I believe there shouldn't be any authentication on the token endpoint.

I tried to configure a custom RP-config without success 
```xml
  <bean parent="RelyingPartyByName" c:relyingPartyIds="https://spa.example.com">
      <property name="profileConfigurations">
        <list>
             <bean parent="OIDC.SSO"  p:tokenEndpointAuthMethods="none" />
             <bean parent="OIDC.UserInfo"/>
             <bean parent="OAUTH2.Revocation"/>
        </list>
      </property>
    </bean>
```

**Comment by hjmikkon** [comment]
In the OIDC.SSO profile confifguration, you've enabled tokenEndpointAuthenticationMethod "none" to be valid for one RP via RelyingPartyByName. However, you also need to configure that in the client metadata, by adding:

```
...
"token_endpoint_auth_method":"none"
...

```
in the client metadata for the corresponding RP. Then this RP is able to access the token endpoint without needing to authenticate itself.

**Comment by gueuselambix** [comment]
It now works, but the code_verifier & code_challange is not validated. Whatever I provide, I get the id_token and access_token at the token endpoint.
It does read the code_verifier value, because it fails when the code_verifier is not 43 chars long, but the verifier is not matched against the challenge.

**Comment by hjmikkon** [comment]
> It now works, but the code_verifier & code_challange is not validated. Whatever I provide, I get the id_token and access_token at the token endpoint.

I was not able to repeat this: they should indeed be validated during the token endpoint flow. When you upgraded into v1.1.0-SNAPSHOT, did you also update the contents of the subdirectories under /opt/shibboleth-idp/flows?

I'm currently updating the Wiki documentation and drafting the release notes. The upgrade process contains more steps than just new copies of JARs.

**Comment by gueuselambix** [comment]
I had to update the flow indeed.
It works now, thank you!
