### ISSUE TITLE
Release policy for OAuth2 scope values based on IdPAttributes

### ISSUE THREAD

**Issue by gueuselambix** [CSCfi/shibboleth-idp-oidc-extension#39]
Hi

I would like to use the OAuth2 _scope_ attribute for authorization purposes on a OAuth2 resource server. For example, the resource server could implement a REST endpoint at /courses and use 2 scopes: courses:read & courses:write

- GET /courses would require scope courses:read
- POST /courses would require scope courses:write
- PUT /courses/1 would require scope courses:write
- etc

The scopes are now all or nothing based on the client's settings. But I would like to restrict who can read and who can write courses based on the available attributes the IdP has access to, e.g. students can only read, faculty can read & write courses.

The OAuth2 client would be allowed to request both scopes, but the context of the user will define which scopes will be granted or not.

**Comment by hjmikkon** [comment]
This sounds very interesting, and it's worth considering to be implemented in the future releases. I'll take it to the backlog.

Note that the additional features will be implemented to the plugin 2.0-codebase, which is compatible with Shibboleth IdP V4+. First beta releases of both IdP and the plugin were released this week, and are available here:

https://shibboleth.net/downloads/identity-provider/
https://shibboleth.net/downloads/identity-provider/extensions/java-idp-oidc/

**Comment by gueuselambix** [comment]
moved to https://issues.shibboleth.net/jira/projects/JOIDC/issues/JOIDC-6
