### ISSUE TITLE
idp install directory hardcoded as "/opt/shibboleth-idp"

### ISSUE THREAD

**Issue by lhoekenga** [CSCfi/shibboleth-idp-oidc-extension#5]
There are hard coded paths to "/opt/shibboleth-idp" in both
    conf/oidc-metadata-providers.xml
    system/conf/services-system.xml

This should be updated to use the idp.home property, e.g.
    <value>%{idp.home}/conf/oidc-metadata-providers.xml</value>

Maybe this is just in the demo IDP set up by vagrant / ansible?

**Comment by jalauros** [comment]
Should not be anymore.
