### ISSUE TITLE
deprecated config

### ISSUE THREAD

**Issue by alanbuxey** [CSCfi/shibboleth-idp-oidc-extension#7]
note some deprecated config on the bootup/creation (bottom of this output)

# vagrant up
Bringing machine 'app' up with 'virtualbox' provider...
==> app: Running provisioner: ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.5.5).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    app: Running ansible-galaxy...
- downloading role 'xml', owned by cmprescott
- downloading role from
https://github.com/cmprescott/ansible-xml/archive/1.0.0.tar.gz
- extracting cmprescott.xml to
/root/shibboleth-idp-oidc-extension/roles/cmprescott.xml
- cmprescott.xml (1.0.0) was installed successfully
- downloading role 'mariadb', owned by CSCfi
- downloading role from
https://github.com/CSCfi/ansible-role-mariadb/archive/v1.0.0.tar.gz
- extracting CSCfi.mariadb to
/root/shibboleth-idp-oidc-extension/roles/CSCfi.mariadb
- CSCfi.mariadb (v1.0.0) was installed successfully
- downloading role 'jetty', owned by CSCfi
- downloading role from
https://github.com/CSCfi/ansible-role-jetty/archive/v1.0.0.tar.gz
- extracting CSCfi.jetty to
/root/shibboleth-idp-oidc-extension/roles/CSCfi.jetty
- CSCfi.jetty (v1.0.0) was installed successfully
- downloading role 'shibboleth-idp', owned by CSCfi
- downloading role from
https://github.com/CSCfi/ansible-role-shibboleth-idp/archive/1.0.1.tar.gz
- extracting CSCfi.shibboleth-idp to
/root/shibboleth-idp-oidc-extension/roles/CSCfi.shibboleth-idp
- CSCfi.shibboleth-idp (1.0.1) was installed successfully
 [WARNING]: - dependency cmprescott.xml from role CSCfi.shibboleth-idp differs
from already installed version (1.0.0), skipping
 [WARNING]: - dependency CSCfi.jetty from role CSCfi.shibboleth-idp differs
from already installed version (v1.0.0), skipping
- downloading role 'apache', owned by CSCfi
- downloading role from
https://github.com/CSCfi/ansible-role-apache/archive/v1.0.0.tar.gz
- extracting CSCfi.apache to
/root/shibboleth-idp-oidc-extension/roles/CSCfi.apache
- CSCfi.apache (v1.0.0) was installed successfully
- downloading role '389-ds', owned by CSCfi
- downloading role from
https://github.com/CSCfi/ansible-role-389-ds/archive/master.tar.gz
- extracting CSCfi.389-ds to
/root/shibboleth-idp-oidc-extension/roles/CSCfi.389-ds
- CSCfi.389-ds (master) was installed successfully
    app: Running ansible-playbook...
[DEPRECATION WARNING]: Using 'port' as a role param has been deprecated. In the
 future, these values should be entered in the `vars:` section for roles, but
for now we'll store it as both a param and an attribute.. This feature will be
removed in version 2.7. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

**Comment by jalauros** [comment]
We see the ansible scripts as our tool for development and as something you may use to test the product easily. For the actual installation we provided archives. The scripts causing the warnings are not maintained by us. I am closing the issue as mostly it is our of our hands.
