### ISSUE TITLE
Shibboleth warnings

### ISSUE THREAD

**Issue by alanbuxey** [CSCfi/shibboleth-idp-oidc-extension#9]
noted these in the idp-warn.log from fresh install

2018-07-02 12:06:25,439 - WARN
[net.shibboleth.idp.attribute.resolver.spring.enc.BaseAttributeEncoderParser:80]
- Configuration contains at least one element in the deprecated
'urn:mace:shibboleth:2.0:attribute:encoder' namespace.
2018-07-02 12:06:25,498 - WARN
[net.shibboleth.idp.attribute.resolver.spring.ad.BaseAttributeDefinitionParser:123]
- Attribute Definition 'email_idtoken': sourceAttributeID was not
specified but is required
2018-07-02 12:06:25,500 - WARN
[net.shibboleth.idp.attribute.resolver.spring.ad.BaseAttributeDefinitionParser:123]
- Attribute Definition 'name_idtoken': sourceAttributeID was not
specified but is required

first is caused by legacy  IdP 2.x statements (those shouldn't appear
in a fresh v3 install...or if the v2 was upgraded to v3.  the last 2
are cleared by adding the relevant sourceAttributeID in
attribute-resolver.xml  ie

    
    <AttributeDefinition id="email_idtoken" xsi:type="Simple"
sourceAttributeID="email_idtoken">
        <Dependency ref="email" />
        <AttributeEncoder xsi:type="oidcext:OIDCString"
placeToIDToken="true" denyUserinfo="true" name="email" />
    </AttributeDefinition>

    
    <AttributeDefinition id="name_idtoken" xsi:type="Simple"
sourceAttributeID="name_idtoken">
        <Dependency ref="name" />
        <AttributeEncoder xsi:type="oidcext:OIDCString"
placeToIDToken="true" denyUserinfo="true" name="name" />
    </AttributeDefinition>

**Comment by jalauros** [comment]
"sourceAttributeID was not specified but is required" should not come from HEAD anymore. 

Configuration contains at least one element in the deprecated 'urn:mace:shibboleth:2.0:attribute:encoder' namespace - warning is not in our hands though. We introduce new org.geant.idpextension.oidc.attribute.encoder namespace for OIDC attributes and Shib namespace verification logic fails as it assumes there are only two namespaces, the deprecated 'urn:mace:shibboleth:2.0:attribute:encoder' and current 'urn:mace:shibboleth:2.0:resolver'. So it mistakes our namespace for  'urn:mace:shibboleth:2.0:attribute:encoder'.

This is only inconvinience, atleast for now.
